openapi: 3.0.3
info:
  title: To Do list App
  version: 1.0.0
paths:
    /task:
        post:
            description: create a new task
            operationId: createNewTask
            responses:
                '201':
                    description: Task created successfully
                    content:
                        application/json:
                            schema:
                                type: Task
                                items:
                                    $ref: '#/components/schemas/taskResponse'
                default:
                    description: Unexpected error
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/taskRequest'
    /task/{taskId}:
        parameters:
            - in: path
              name: taskId
              required: true
              schema:
                  type: array
                  items:
                      type: string
        get:
            description: returns a single task from the system
            operationId: getTask
            responses:
                '200':
                    description: Task response
                    content:
                        application/json:
                            schema:
                                type: Task
                                items:
                                    $ref: '#/components/schemas/taskResponse'
                '400':
                    description: Invalid request
                default:
                    description: Unexpected error
        put:
            description: change task status
            operationId: updateTask
            responses:
                '201':
                    description: Task created successfully, no content to return
                '204':
                    description: Task updated successfully, no content to return
                '400':
                    description: Invalid request
                default:
                    description: Unexpected error
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/taskRequest'
    /tasks:
        get:
            description: returns all tasks from the system
            operationId: getAllTasks
            responses:
                '200':
                    description: A list of tasks
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/taskResponse'
                '400':
                    description: Invalid request
                default:
                    description: Unexpected error

components:
    schemas:
        taskResponse:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                description:
                    type: string
                status:
                    type: string
                    enum:
                        - finished
                        - doing
                        - not_started
                startDate:
                    type: string
                finishedDate:
                    type: string
        taskRequest:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                description:
                    type: string
                status:
                    type: string
                    enum:
                        - finished
                        - doing
                        - not_started
