
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn clean install -DskipTests
      - name: Unit Tests
        run: mvn jacoco:prepare-agent surefire:test
      - name: Integration Tests
        run: mvn jacoco:prepare-agent-integration failsafe:integration-test
      - name: Unit Test Coverage
        run: mvn jacoco:report
      - name: Integration Test Coverage
        run: mvn jacoco:report-integration
      - name: Jacoco Aggregate
        run: mvn jacoco:report-aggregate
#      - name: Jacoco Coverage Report
#        uses: PavanMudigonda/jacoco-reporter@v4.9
#        with:
#          coverage_results_path: ${{ github.workspace }}/reportAggregate/target/site/jacoco-aggregate/jacoco.xml
#          coverage_report_name: Coverage
#          coverage_report_title: JaCoCo
#          skip_check_run: false
#          minimum_coverage: 50
#          publish_only_summary: false
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
          jacoco-csv-file: reportAggregate/target/site/jacoco-aggregate/jacoco.csv
          generate-coverage-endpoint: true
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'francisco.barbosa'
            git config --global user.email 'francisco.barbosa@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: reportAggregate/target/site/jacoco-aggregate/*


