
name: Build with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: mvn clean install -DskipTests
      - name: Unit Tests
        run: mvn jacoco:prepare-agent surefire:test
      - name: Integration Tests
        run: mvn jacoco:prepare-agent-integration failsafe:integration-test
      - name: Unit Test Coverage
        run: mvn jacoco:report
      - name: Integration Test Coverage
        run: mvn jacoco:report-integration